main: ${project.groupId}.${project.artifactId}
name: ${project.artifactId}
version: ${project.version}
authors: [ Valentina_pro ]
api-version: 1.18
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
description: Create and worship your own Gods
commands:
  gods:
    description: Opens the god interface
    usage: /gods

permissions:
  newgods.divorce:
    description: Divorces your partner
    default: true
  newgods.gods:
    description: Opens the gods interface
    default: true
  newgods.help:
    description: Gives a list of commands
    default: true
  newgods.home:
    description: Teleports you to your religions home
    default: true
  newgods.info:
    description: Allows you to get information about your god
    default: true
  newgods.invite:
    description: Lets people invite others to their religion
    default: true
  newgods.leave:
    description: Allows players to leave their god
    default: true
  newgods.list:
    description: Lets people list the gods on the server
    default: true
  newgods.marry:
    description: Lets people marry others
    default: true
  newgods.rank:
    description: Lets religious leaders rank people to priests
    default: true
  newgods.sethome:
    description: Leaders can set their religions /home location
    default: true
  newgods.pray:
    description: Lets people pray to their gods
    default: true
  newgods.create:
    description: This lets people create their own gods
    default: op
  newgods.type:
    description: Allows you to change your gods type
    default: true
  newgods.halfpraytime:
    description: You can wait half the time to pray again
    default: op
  newgods.doublexp:
    description: Gods will give you double xp
    default: op
  newgods.admin:
    description: Access to admin commands
    default: op